version: '3.8'
services:
  mysqldb:
    image: mysql:5.7.37
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
      - ./devops/db.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_ROOT_PASSWORD: 'grouping'
      MYSQL_DATABASE: 'grouping'
    expose:
      - "3307"
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 20
  app:
    container_name: "grouping-app"
    depends_on:
      mysqldb:
        condition: service_healthy
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DB_HOST: mysqldb
      DB_USER: "root"
      DB_PASSWORD: grouping
      DB_NAME: grouping
      DB_PORT: 3306
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - uploads:/app/uploads

volumes:
  db:
  uploads: