version: '3.8'
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=grouping
      - MYSQL_DATABASE=grouping
    volumes:
      - db:/var/lib/mysql
      - ${PWD}/db.sql:/docker-entrypoint-initdb.d/start.sql
    ports:
      - "3307:3306"
  app:
    container_name: "grouping-app"
    depends_on:
      - mysqldb
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DB_HOST: mysqldb
      DB_USER: "root"
      DB_PASSWORD: grouping
      DB_NAME: grouping
      DB_PORT: 3306
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - uploads:/app/uploads

volumes:
  db:
  uploads: